// Asserts every `fixtures/library/library-*.bin` against its `.json`
// golden (same discipline as `telemetry.fixture.test.ts`/
// `info.fixture.test.ts`) -- FERN DESIGN section 5: "core emits, JS
// asserts". The fixtures were generated by
// `core/src/app/library_fixtures.rs` (bead pico-link-jyhk.18); none of them
// happen to carry EQ bands, so `library-golden.bin`'s effect blob is
// additionally decoded and checked field-by-field below to prove
// `decodePresetBlob` actually reads the 80-byte v2 blob, not just the
// header/name that the JSON golden already covers.
import { describe, expect, it } from "vitest";
import { decodeLibrarySnapshot, decodePresetBlob, EFFECT_RECORD_LEN } from "./library";
import type { LibraryDevice, LibraryEffect, LibrarySnapshot } from "./library";
import { libraryFixtureBytes, libraryFixtureJson, libraryFixtureNames } from "../test/fixtures";

interface FixtureEffect {
  id: number;
  persisted_seq: number;
  preset_name: string;
}

interface FixtureDevice {
  addr: string;
  preset_id: number;
  connected: boolean;
  name: string;
}

interface FixtureLibrarySnapshot {
  wire_len: number;
  library_rev: number;
  presets_ready: boolean;
  max_effects: number;
  max_devices: number;
  effects: FixtureEffect[];
  devices: FixtureDevice[];
}

function expectedEffect(fixture: FixtureEffect, decoded: LibraryEffect): void {
  expect(decoded.id).toBe(fixture.id);
  expect(decoded.persistedSeq).toBe(fixture.persisted_seq);
  expect(decoded.preset.name).toBe(fixture.preset_name);
}

function expectedDevice(fixture: FixtureDevice, decoded: LibraryDevice): void {
  expect(decoded.addr).toBe(fixture.addr);
  expect(decoded.presetId).toBe(fixture.preset_id);
  expect(decoded.connected).toBe(fixture.connected);
  expect(decoded.name).toBe(fixture.name);
}

describe("decodeLibrarySnapshot vs fixtures/library/library-*.bin+json", () => {
  const names = libraryFixtureNames();

  it("found the expected fixture set (guards against an empty/missing dir silently passing)", () => {
    expect(names.length).toBeGreaterThanOrEqual(7);
    expect(names).toContain("library-golden");
    expect(names).toContain("library-empty");
    expect(names).toContain("library-max-effects-and-devices");
  });

  it.each(names)("%s", (name) => {
    const bytes = libraryFixtureBytes(`${name}.bin`);
    const fixture = libraryFixtureJson<FixtureLibrarySnapshot>(`${name}.json`);
    expect(fixture.wire_len).toBe(bytes.byteLength);

    const decoded = decodeLibrarySnapshot(bytes);
    expect(decoded).not.toBeNull();
    const snap = decoded as LibrarySnapshot;

    expect(snap.libraryRev).toBe(fixture.library_rev);
    expect(snap.presetsReady).toBe(fixture.presets_ready);
    expect(snap.maxEffects).toBe(fixture.max_effects);
    expect(snap.maxDevices).toBe(fixture.max_devices);
    expect(snap.effects.length).toBe(fixture.effects.length);
    expect(snap.devices.length).toBe(fixture.devices.length);
    fixture.effects.forEach((e, i) => expectedEffect(e, snap.effects[i]));
    fixture.devices.forEach((d, i) => expectedDevice(d, snap.devices[i]));
  });

  it("decodes library-golden's effect blob field-by-field, not just its name (the 80-byte v2 blob)", () => {
    const bytes = libraryFixtureBytes("library-golden.bin");
    const snap = decodeLibrarySnapshot(bytes)!;
    expect(snap.effects).toHaveLength(1);

    // The fixture was built from `Preset::new("Warm")` -- no bands, no
    // crossfeed, an auto (not imported) preamp, unlocked. Cross-checked
    // directly against the blob bytes at the record's offset (14 +
    // EFFECT_RECORD_LEN's id/persisted_seq prefix), not just via the
    // decoder under test, so this test would fail if both the encoder and
    // decoder shared the same bug.
    const HEADER_LEN = 14;
    const blobOff = HEADER_LEN + 4; // past id (u16) + persisted_seq (u16)
    const blob = bytes.subarray(blobOff, blobOff + EFFECT_RECORD_LEN - 4);
    expect(blob[0]).toBe(2); // blob version 2
    const preset = decodePresetBlob(blob);

    expect(preset).toEqual(snap.effects[0].preset);
    expect(preset.name).toBe("Warm");
    expect(preset.crossfeed).toBe("off");
    expect(preset.bands).toEqual([]);
    expect(preset.preamp).toEqual({ kind: "auto" });
    expect(preset.eqLocked).toBe(false);
  });

  it("rejects an unknown lib_proto", () => {
    const bytes = libraryFixtureBytes("library-empty.bin").slice();
    bytes[0] = 99;
    expect(decodeLibrarySnapshot(bytes)).toBeNull();
  });

  it("rejects a payload shorter than its own declared header", () => {
    expect(decodeLibrarySnapshot(new Uint8Array(13))).toBeNull();
  });
});
