// Loads the neutral-path fixtures at `fixtures/telemetry/` and
// `fixtures/library/` (repo root, sibling of `web/`) for host-side tests.
// Not part of the app bundle -- `node:fs` only works in the test/Node
// process, never imported outside `*.test.ts` files. FERN DESIGN section 5:
// "core emits, JS asserts"; these fixtures are the neutral contract,
// generated by `cargo test` (`UPDATE_FIXTURES=1`) except `info-v1.*`, which
// is hand-written (see its own `_comment`).
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_ROOT = path.resolve(HERE, "../../../fixtures");
export const FIXTURES_DIR = path.join(FIXTURES_ROOT, "telemetry");
export const LIBRARY_FIXTURES_DIR = path.join(FIXTURES_ROOT, "library");
export const HOST_OP_FIXTURES_DIR = path.join(FIXTURES_ROOT, "host_op");
export const RADIO_FIXTURES_DIR = path.join(FIXTURES_ROOT, "radio");

export function fixtureBytes(name: string): Uint8Array {
  return new Uint8Array(readFileSync(path.join(FIXTURES_DIR, name)));
}

export function fixtureJson<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(FIXTURES_DIR, name), "utf-8")) as T;
}

/** Every `home-*.bin` fixture's base name (without extension), each paired with a same-named `.json`. */
export function homeSnapshotFixtureNames(): string[] {
  return readdirSync(FIXTURES_DIR)
    .filter((f) => f.startsWith("home-") && f.endsWith(".bin"))
    .map((f) => f.slice(0, -".bin".length));
}

export function libraryFixtureBytes(name: string): Uint8Array {
  return new Uint8Array(readFileSync(path.join(LIBRARY_FIXTURES_DIR, name)));
}

export function libraryFixtureJson<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(LIBRARY_FIXTURES_DIR, name), "utf-8")) as T;
}

/** Every `library-*.bin` fixture's base name (without extension), each paired with a same-named `.json`. */
export function libraryFixtureNames(): string[] {
  return readdirSync(LIBRARY_FIXTURES_DIR)
    .filter((f) => f.startsWith("library-") && f.endsWith(".bin"))
    .map((f) => f.slice(0, -".bin".length));
}

export function hostOpFixtureBytes(name: string): Uint8Array {
  return new Uint8Array(readFileSync(path.join(HOST_OP_FIXTURES_DIR, name)));
}

export function hostOpFixtureJson<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(HOST_OP_FIXTURES_DIR, name), "utf-8")) as T;
}

/** Every `request-*.bin` fixture's base name (without extension), each paired with a same-named `.json`. */
export function hostOpRequestFixtureNames(): string[] {
  return readdirSync(HOST_OP_FIXTURES_DIR)
    .filter((f) => f.startsWith("request-") && f.endsWith(".bin"))
    .map((f) => f.slice(0, -".bin".length));
}

/** Every `status-*.bin` fixture's base name (without extension), each paired with a same-named `.json`. */
export function hostOpStatusFixtureNames(): string[] {
  return readdirSync(HOST_OP_FIXTURES_DIR)
    .filter((f) => f.startsWith("status-") && f.endsWith(".bin"))
    .map((f) => f.slice(0, -".bin".length));
}

export function radioFixtureBytes(name: string): Uint8Array {
  return new Uint8Array(readFileSync(path.join(RADIO_FIXTURES_DIR, name)));
}

export function radioFixtureJson<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(RADIO_FIXTURES_DIR, name), "utf-8")) as T;
}

/** Every `radio-*.bin` fixture's base name (without extension), each paired with a same-named `.json`. */
export function radioFixtureNames(): string[] {
  return readdirSync(RADIO_FIXTURES_DIR)
    .filter((f) => f.startsWith("radio-") && f.endsWith(".bin"))
    .map((f) => f.slice(0, -".bin".length));
}
