// Loads the neutral-path fixtures at `fixtures/telemetry/` (repo root,
// sibling of `web/`) for host-side tests. Not part of the app bundle --
// `node:fs` only works in the test/Node process, never imported outside
// `*.test.ts` files. FERN DESIGN section 5: "core emits, JS asserts";
// these fixtures are the neutral contract, generated by `cargo test`
// (`UPDATE_FIXTURES=1`) except `info-v1.*`, which is hand-written (see its
// own `_comment`).
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const FIXTURES_DIR = path.resolve(HERE, "../../../fixtures/telemetry");

export function fixtureBytes(name: string): Uint8Array {
  return new Uint8Array(readFileSync(path.join(FIXTURES_DIR, name)));
}

export function fixtureJson<T>(name: string): T {
  return JSON.parse(readFileSync(path.join(FIXTURES_DIR, name), "utf-8")) as T;
}

/** Every `home-*.bin` fixture's base name (without extension), each paired with a same-named `.json`. */
export function homeSnapshotFixtureNames(): string[] {
  return readdirSync(FIXTURES_DIR)
    .filter((f) => f.startsWith("home-") && f.endsWith(".bin"))
    .map((f) => f.slice(0, -".bin".length));
}
